config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :users
  resources :questions do
    resources :responses
  end
  resources :votes, only: [:create]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'logout', to: "sessions#destroy"
  get 'guest', to: "sessions#guest"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :responses
  belongs_to :best_response, class_name: 'Response'
  validates :title, presence: true
  validates :body, presence: true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes
  validates :body, presence: true

  def vote_count
    self.votes.count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :responses
  has_many :votes
  validates :username, presence: true
  validates_uniqueness_of :username
  validates_length_of :password, minimum: 8
  has_secure_password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :response
  validates :user_id, uniqueness: {scope: :response_id}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    if current_user != nil
      @question = Question.new(question_params)
      @question.user_id = current_user.id
      if @question.save
        respond_to do |format|
          format.html do
            flash[:notice] = "Question added!"
            redirect_to user_path(current_user)
          end
          format.js { flash.now[:notice] = "Question added!" }
        end
      else
        respond_to do |format|
          format.html do
            flash[:error] = "Question not added."
            render :new
          end
          format.js do
            render :error
          end
        end


      end
    else
      redirect_to users_path
    end
  end

  def update
    @question = Question.find(params[:id])
    if current_user == @question.user
      @question.best_response = Response.find(params[:question][:best_response_id].to_i)
      @question.save
    end
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:id])
    Response.all.each do |response|
      if response.question == @question
        response.destroy
      end
    end
    @question.destroy
    redirect_to user_path(current_user)
  end

private
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @user = @question.user
    @response = Response.new
  end

  def create
    @response = current_user.responses.new(response_params)
    @response.question_id = params[:question_id]
    if @response.save
      flash[:notice] = "Response added!"
      UserMailer.responded(@response).deliver
      redirect_to question_path(@response.question)
    else
      flash[:error] = "Failure."
      render :new
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to :back
  end

  private
    def response_params
      params.require(:response).permit(:body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      flash[:notice] = 'You are logged in!'
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = 'Unsuccessful login attempt!'
      render 'new'
    end
  end

  def guest
    user = User.find_by(username: 'guest@answer.me')
    if user && user.authenticate('password')
      flash[:notice] = 'You are logged in!'
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = 'Unsuccessful login attempt!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You are now logged out.'
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'You successfully registered!'
      session[:user_id] = @user.id
      UserMailer.signup_confirmation(@user).deliver
      redirect_to root_path
    else
      flash[:error] = 'Errors in your submission. Try again.'
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = Vote.new(vote_params)
    vote.user = current_user
    vote.save
    redirect_to question_path(vote.response.question)
    # alternate method:
    # response = Response.find(vote_params[:response_id])
    # Vote.create(user_id: user.id, response_id: response.id)
    # redirect_to question_path(response.question)
  end
private
  def vote_params
    params.require(:vote).permit(:response_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">S.Lavaflow</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/users">Users</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/logout">Logout</a></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/login">Login</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnswerMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="row" id="new-question-panel">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          New Question
        </h3>
      </div>
      <div class="panel-body">
        <%= bootstrap_form_for @question, remote: true do |f| %>
          <span id="new_question_errors"></span>
          <div class="form-group">
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.text_area :body %>
          </div>
          <%= f.submit "Create Question", class: "btn btn-warning", id: "question_create_btn"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/questions/_listed_question.html.erb
<li class="list-group-item">
  <%= link_to question.title, question_path(question) %>
  <small> <%= distance_of_time_in_words_to_now(question.created_at) %> ago</small>
  <% if question.user == current_user %>
    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, question_path(question), method: :delete, id: "delete_question_#{question.id}"%>
  <% end %>
  <span class="pull-right">
    Responses
    <span class="badge">
      <%= question.responses.count %>
    </span>
  </span>
</li>

app/views/questions/_question.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= question.title %>
          <span class="pull-right"><%= question.user.username %></span>
        </h3>
      </div>
      <div class="panel-body">
        <span><%= question.body %></span>
        <small class="pull-right"><%= distance_of_time_in_words_to_now(question.created_at) %> ago</small>
        <br>
        <% if question.user == current_user %>
          <%= link_to '<i class="glyphicon glyphicon-trash pull-right"></i>'.html_safe, question_path(question), method: :delete, id: "delete_question_#{question.id}"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/questions/create.js.erb
$('#new-question-panel').remove();
$('#add-question-btn').show();
$('#question-list-panel').append('<%= j render partial: 'questions/listed_question', locals: {question: @question} %>');

app/views/questions/error.js.erb
$("#new_question_errors").text("Please fill in both fields.");

app/views/questions/index.html.erb
<div class="row">
<div class="col-sm-2"></div>

<div class="col-sm-8">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Questions <span class="badge"><%= @questions.count %></span></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <%= render partial: 'listed_question', collection: @questions, as: :question %>
      </ul>
    </div>
  </div>

<%= link_to "Add question", new_question_path, class: "btn btn-default btn-lg btn-block" %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/new.js.erb
$('#add-question-btn').hide().after('<%= j render("form") %>');

app/views/questions/show.html.erb
<%= render @question %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <% if current_user != nil %>
      <%= link_to "Leave a response", new_question_response_path(@question), class: "btn btn-default btn-lg btn-block" %>
    <% end %>
  </div>
</div>

<div class="row">
    <% if @question.responses.any? %>
      <div class="col-sm-8 col-sm-offset-2" id="responses-display">

      <h4>Responses:</h4>

      <% if @question.best_response %>
        <div class="best-response-display panel panel-info">

          <div class="panel-heading">
            <strong>Selected Best Response</strong>
            <span class="pull-right">Votes <span class="badge"><%= @question.best_response.votes.count %></span></span>
            <br>
            <%= @question.best_response.user.username %>
          </div>

          <div class="panel-body">
            &ldquo;<%= @question.best_response.body %>&rdquo;
            <small class="pull-right">
              <%= distance_of_time_in_words_to_now(@question.best_response.created_at) %> ago
            </small>
            <br>
            <div class="pull-right">
              <%= bootstrap_form_for Vote.new do |f| %>

                <%= f.hidden_field :response_id, :value => @question.best_response.id %>
                <button type="submit" class="btn btn-default btn-xs">+1</button>
              <% end %>
            </div>
          </div>

        </div>
      <% end %>

      <% @question.responses.sort_by(&:vote_count).reverse.each do |response| %>
        <% unless response == @question.best_response %>
          <%= render response %>
        <% end %>
      <% end %>

      </div>
    <% end %>

</div> <!-- end row -->

app/views/questions/xxx_destroy.js.erb
console.log('delete test')
// $("#question_<%= @question.id %>").remove();

app/views/responses/_form.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">
          Response to <%= @question.title %>
        </h3>
      </div>
      <div class="panel-body">
        <%= bootstrap_form_for([@question, @response]) do |f| %>
          <div class="form-group">
            <%= f.text_area :body %>
          </div>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/responses/_response.html.erb
<div class="panel panel-primary">

  <div class="panel-heading">
    <%= response.user.username %>
    <span class="pull-right">Votes <span class="badge"><%= response.votes.count %></span></span>
  </div> <!-- end panel-heading -->

  <div class="panel-body">
    &ldquo;<%= response.body %>&rdquo;
    <small class="pull-right">
      <%= distance_of_time_in_words_to_now(response.created_at) %> ago
    </small>
    <br>

    <% if logged_in? %>
      <span class="">
        <% if response.user == current_user %>
          <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, question_response_path(response.question,response), method: :delete, id: "delete_response_#{response.id}"%>
        <% end %>
      </span>
      <span class="plusone pull-right">
        <%= bootstrap_form_for Vote.new do |f| %>
          <%= f.hidden_field :response_id, :value => response.id %>
          <button type="submit" class="btn btn-default btn-xs">+1</button>
        <% end %>
      </span>
    <% end %>

    <div class="response">
      <% if current_user == @question.user %>
        <%= bootstrap_form_for @question do |f| %>
          <input name="_method" type="hidden" value="patch">
          <%= f.hidden_field :best_response_id, :value => response.id %>
          <button type="submit" class="btn btn-default btn-xs">mark as best</button>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/responses/new.html.erb
<%= render @question %>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= bootstrap_form_for @user do |f| %>
  <div class="form-group">
    <%= f.text_field :username %>
  </div>

  <div class="form-group">
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit 'Create User', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Users <span class="badge"><%= @users.count %></span></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <% @users.each do |user| %>
            <li class="list-group-item">
              <%= link_to user.username, user_path(user), id: "user-link-#{user.id}" %>
              <span class="pull-right">Questions <span class="badge"><%= user.questions.count %></span></span>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "Add user", new_user_path, class: "btn btn-default btn-lg btn-block" %>
</div>
<div class="col-sm-2"></div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 well">
    <h3>New user</h3>
    <%= render 'form' %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h2><%= @user.username %></h2>

    <% if @user.questions.any? %>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">My Questions <span class="badge"><%= @user.questions.count %></span></h3>
      </div>
      <div class="panel-body">
        <ul class="list-group" id="question-list-panel">
          <% @user.questions.each do |question| %>
            <%= render partial: 'questions/listed_question', locals: {question: question} %>
          <% end %>
        </ul>
      </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>

<div class="row" id="add-question-btn">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <% if @user == current_user %>
      <%= link_to "Add question", new_question_path, class: "btn btn-default btn-lg btn-block", remote: true %>
    <% end %>
    <hr>
  </div>
  <div class="col-sm-2"></div>
</div>

<div class="row" id="add-question-btn">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <% if @user.responses.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">My Responses <span class="badge"><%= @user.responses.count %></span></h3>
      </div>
      <div class="panel-body">
        <ul class="list-group">
          <% @user.responses.each do |response| %>
            <li class="list-group-item">
              <%= link_to response.question.title, question_path(response.question) %>
              <small>
                <%= distance_of_time_in_words_to_now(response.created_at) %> ago
              </small>
            </li>
          <% end %>
        </ul>
      </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-2"></div>

</div>